const eg0A = [
    "R' F2 R U R' F R",
    "R' U F2 U F2 U' R U R' F' R",
    "F R' F' R U R U2 R' F R' F' R",
    "R2 U R' U' R' F R F' R'",
    "R' F U2 R U R' U2 R' F' R",
    "R U' R2 U R U F R' F' R U R'",

    "R' F' R U2 R' F' R U2 R' F R",
    "R U2 R' F R' F' R U' R U' R'",
    "R2 U R2 F' U F R2 U' R2",
    "F' R U R' F U F'",
    "R U2 R' U' R U' R' F R' F' R U R U' R'",
    "R2 F R F' U' R U2 R' U2 R",

    "R U R' U2 R U R' U' R U2 R'",
    "R' F R U2 F' R U R' U2 R' F' R",
    "R' F' R U' R' F' R F' R U R'",
    "F R' F' R U' R U' R' U R' F R F'",
    "R' F2 R U R' F' R U2 R U' R' F",
    "F' U R U R' U2 F R' F2 R",

    "R U F R' F' R'",
    "F' U R U' R U' R2 F2 R U2 R' F R' F'",
    "F' U F U R U R' U2 R' F R F'",
    "R' F' R F R U R2 F' R U R U' R'",
    "R' F R' F' U' R U' R' U2 R2",
    "R' F R F' R U R2 F' R U R U' R' F",

    "F R F' R U R' U' R'",
    "F' U R U' R' F R' F' R F",
    "R2 F' R U R U' R' F R U' R' U R",
    "R U' R U' R U2 R' U R' U R'",
    "R U R U' R2 U R U F R2 F'",
    "F R' F' R U2 F R' F' R U' R U' R'",

    "R U' R' U' F' U F",
    "R U2 F R' F' U2 R'",
    "R' U' R' U R' F R F' R U' R2",
    "R2 F2 U' R' U F' R U' R",
    "F R' F' R U' R U2 R' U' R U2 R'",
    "R U' R' U' F R' F' R2 U' R'",

    "R2 U2 R' U2 RU",
    "R2 F R2 F2 U2 F R2",
    "R U2 R' U' R U' R2 F R F' R U R'",
    "F R' F' R U2 R U R' F R' F' R",
];
