const eg2A = [
    "R2 F' R' F' R U' R U R2 U2 R",
    "R2 F2 R U2 R U R' U R",
    "R2 B2 R' U' R' F R' F' R",
    "F R2 F' R2 F' R U' R",
    "R' F2 R U2 R U' R' F R2 B2 R2",
    "R U' R' F R' F' R' F2 R2",
    "R2 F2 U R U2 R' F R2 F' R",
    "R2 B2 R' U2 R' U' R U' R'",
    "R2 F2 R F R F' R U R'",
    "R' U R' F R2 F R2 F'",
    "R U' R U2 R U' R F",
    "R' F R F' R U R B2 R2",
    "F R U' R U R' U2 R' U F'",
    "F R2 F2 R U R2 U2 R",
    "R' U' R U2 R2 F' R U' F R",
    "R' U2 F2 R U' R' U F' R",
    "R' U2 R U' R2 F2 R F R",
    "R' F' R' F2 R2 U R' U2 R",
    "F U R U2 R U R' U2 R' U F'",
    "B2 R2 F' U R U' R' F'",
    "R U R' U' R B2 R' U R U' R'",
    "R' F R' F' R2 U2 R' U' R' F2 R2",
    "F R' F' R U R U' R B2 R2",
    "R U R U' R' F R' F' R2 B2 R2",

    "R U R' U' R' F R F' R2 B2 R2", 
    "F R F' R U R' U' R B2 R2",
    "R' F' U2 R U2 R' F2 U R",
    "R2 B2 R' U2 R' F R' F' R2 U2 R'",
    "R2 B2 R' U R' U' R' F R F'",
    "R2 F2 R F' R U R U' R' F",

    "R2 B2 R' U R U' R' F R' F'",
    "R2 B2 R2 F R' F' R U R U' R'",
    "R2 U' R' U F' R U' R",
    "R' U' R' F R F' U R' F2 R2",
    "R' U R' F' R U' R U R' F2 R",
    "R' F2 R' F2 R U2 R",

    "R2 F R2 F2 U2 F' R2",
    "R2 B2 U2 R' U2 R2",
    "R' F' U R' F R2 U2 R' U R",
    "R B' U R' U' R B2 U2 R'"
];