const eg2A = [
    { scramble: "R2 F' R' F' R U' R U R2 U2 R",  solution: "(U2) R' U R U' R2 F R F' R U R' U' R' F2 R2", img: "../../../2x2/CLL/img/antisune1.png"},
    { scramble: "R2 F2 R U2 R U R' U R",  solution: "R' U' R U' R' U2 R' F2 R2", img: "../../../2x2/CLL/img/antisune2.png"},
    { scramble: "R2 B2 R' U' R' F R' F' R",  solution: "(U2) R' F R F' R U R B2 R2", img: "../../../2x2/CLL/img/antisune3.png"},
    { scramble: "F R2 F' R2 F' R U' R",  solution: "(U') R' U R' F R2 F R2 F'", img: "../../../2x2/CLL/img/antisune4.png"},
    { scramble: "R' F2 R U2 R U' R' F R2 B2 R2",  solution: "R2 B2 R2 F' R U R' U2 R' F2 R", img: "../../../2x2/CLL/img/antisune4.png"},
    { scramble: "R U' R' F R' F' R' F2 R2",  solution: "(U2) R2 F2 R F R F' R U R'", img: "../../../2x2/CLL/img/antisune5.png"},

    { scramble: "R2 F2 U R U2 R' F R2 F' R",  solution: "(U') R' F R2 F' R U2 R' U' F2 R2", img: "../../../2x2/CLL/img/sune1.png"},
    { scramble: "R2 B2 R' U2 R' U' R U' R'",  solution: "R U R' U R U2 R B2 R2", img: "../../../2x2/CLL/img/sune2.png"},
    { scramble: "R2 F2 R F R F' R U R'",  solution: "R U' R' F R' F' R' F2 R2", img: "../../../2x2/CLL/img/sune3.png"},
    { scramble: "R' U R' F R2 F R2 F'",  solution: "(U) F R2 F' R2 F' R U' R", img: "../../../2x2/CLL/img/sune4.png"},
    { scramble: "R U' R F' U2 R U' R F",  solution: "F' R' U R' U2 F R' U R'", img: "../../../2x2/CLL/img/sune5.png"},
    { scramble: "R' F R F' R U R B2 R2",  solution: "R2 B2 R' U' R' F R' F' R", img: "../../../2x2/CLL/img/sune6.png"},

    { scramble: "F R U' R U R' U2 R' U F'",  solution: "F U' R U2 R U' R' U R' F'", img: "../../../2x2/CLL/img/pi1.png"},
    { scramble: "F R2 F2 R U R2 U2 R",  solution: "R' U2 R2 U' R' F2 R2 F'", img: "../../../2x2/CLL/img/pi2.png"},
    { scramble: "R' U' R U2 R2 F' R U' F R",  solution: "(U2) R' F' U R' F R2 U2 R' U R", img: "../../../2x2/CLL/img/pi3.png"},
    { scramble: "R' U2 F2 R U' R' U F' R",  solution: "(U) R' F U' R U R' F2 U2 R", img: "../../../2x2/CLL/img/pi4.png"},
    { scramble: "R' U2 R U' R2 F2 R F R",  solution: "(U') R' F' R' F2 R2 U R' U2 R", img: "../../../2x2/CLL/img/pi5.png"},
    { scramble: "R' F' R' F2 R2 U R' U2 R",  solution: "(U) R' U2 R U' R2 F2 R F R", img: "../../../2x2/CLL/img/pi6.png"},

    { scramble: "F U R U2 R U R' U2 R' U F'",  solution: "F U' R U2 R U' R' U2 R' U' F'", img: "../../../2x2/CLL/img/u1.png"},
    { scramble: "B2 R2 F' U R U' R' F'",  solution: "F R U R' U' F R2 B2", img: "../../../2x2/CLL/img/u2.png"},
    { scramble: "R U R' U' R B2 R' U R U' R'",  solution: "(U) R U R' U' R B2 R' U R U' R'", img: "../../../2x2/CLL/img/u3.png"},
    { scramble: "R' F R' F' R2 U2 R' U' R' F2 R2",  solution: "R2 F2 R U R U2 R2 F R F' R", img: "../../../2x2/CLL/img/u4.png"},
    { scramble: "F R' F' R U R U' R B2 R2",  solution: "(U') R2 B2 R' U R' U' R' F R F'", img: "../../../2x2/CLL/img/u5.png"},
    { scramble: "R U R U' R' F R' F' R2 B2 R2",  solution: "(U') R2 B2 R2 F R F' R U R' U' R'", img: "../../../2x2/CLL/img/u6.png"},

    { scramble: "R U R' U' R' F R F' R2 B2 R2",  solution: "R2 B2 R2 F R' F' R U R U' R'", img: "../../../2x2/CLL/img/l1.png"},
    { scramble: "F R F' R U R' U' R B2 R2",  solution: "(U) R2 B2 R' U R U' R' F R' F'", img: "../../../2x2/CLL/img/l2.png"},
    { scramble: "R' F' U2 R U2 R' F2 U R",  solution: "R' U' F2 R U2 R' U2 F R", img: "../../../2x2/CLL/img/l3.png"},
    { scramble: "R2 B2 R' U2 R' F R' F' R2 U2 R'",  solution: "(U2) R' U' R U R' F' R U R' U' R' F' R2", img: "../../../2x2/CLL/img/l4.png"},
    { scramble: "R2 B2 R' U R' U' R' F R F'",  solution: "F R' F' R U R U' R B2 R2", img: "../../../2x2/CLL/img/l5.png"},
    { scramble: "R2 F2 R F' R U R U' R' F",  solution: "(U) F' R U R' U' R' F R' F2 R2", img: "../../../2x2/CLL/img/l6.png"},

    { scramble: "R2 B2 R' U R U' R' F R' F'",  solution: "F R F' R U R' U' R B2 R2", img: "../../../2x2/CLL/img/t1.png"},
    { scramble: "R2 B2 R2 F R' F' R U R U' R'",  solution: "R U R' U' R' F R F' R2 B2 R2", img: "../../../2x2/CLL/img/t2.png"},
    { scramble: "R2 U' R' U F' R U' R",  solution: "(U2) R' U R' F U' R U R2", img: "../../../2x2/CLL/img/t3.png"},
    { scramble: "R' U' R' F R F' U R' F2 R2",  solution: "(U) R2 F2 R U' F R' F' R U R", img: "../../../2x2/CLL/img/t4.png"},
    { scramble: "R' U R' F' R U' R U R' F2 R",  solution: "(U2) R' F2 R U' R' U R' F R U' R", img: "../../../2x2/CLL/img/t5.png"},
    { scramble: "R' F2 R' F2 R U2 R",  solution: "(U2) R' U2 R' F2 R F2 R", img: "../../../2x2/CLL/img/l1.png"},

    { scramble: "R2 F R2 F2 U2 F' R2",  solution: "(U/U') R2 F U2 F2 R2 F' R2", img: "../../../2x2/CLL/img/h1.png"},
    { scramble: "R2 B2 U2 R' U2 R2",  solution: "R2 U2 R' U2 F2 R2", img: "../../../2x2/CLL/img/h2.png"},
    { scramble: "R' F' U R' F R2 U2 R' U R",  solution: "R' U' R U2 R2 F' R U' F R", img: "../../../2x2/CLL/img/h3.png"},
    { scramble: "R B' U R' U' R B2 U2 R'",  solution: "R U2 B2 R' U R U' B R'", img: "../../../2x2/CLL/img/h4.png"},
];
